name: Metrics
on:
  schedule: [{ cron: "0 2 * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # Core Profile
      - name: Core metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/core.svg
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Calcutta

      # Leetcode
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/leetcode.svg
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: kaushik-yadav
          plugin_leetcode_sections: solved
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
